/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_project_easyanalysis_Exp1 */

#ifndef _Included_com_project_easyanalysis_Exp1
#define _Included_com_project_easyanalysis_Exp1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_project_easyanalysis_Exp1
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_project_easyanalysis_Exp1_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
